services:
  db:
    build: { context: ., dockerfile: Dockerfile.db }
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=defhack
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    ports: ["9000:9000","9001:9001"]
    volumes: ["./minio-data:/data"]

  api:
    build: { context: ., dockerfile: Dockerfile.api }
    env_file: [.env]
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
    ports: ["8080:8080"]

volumes:
  postgres_data: