FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY DefHack ./DefHack
COPY alembic ./alembic
COPY alembic.ini .
CMD ["uvicorn","DefHack.api:app","--host","0.0.0.0","--port","8080"]