version: '3.8'
services:
  postgres:
    image: ankane/pgvector:latest
    container_name: sensor_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: strong_password
      POSTGRES_DB: sensor_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: